apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fm-db-data
  # namespace set by overlay
  labels:
    app: firewall-manager
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-worker
  resources:
    requests:
      storage: 10Gi