apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - routeros-service-endpointslice.yaml
  - routeros-kong-plugins.yaml
  - routeros-request-transformer-plugin.yaml
  - routeros-ingress.yaml
  - routeros-consumer.yaml
