apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: headlamp
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: headlamp-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/headlamp
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/headlamp
        property: OAUTH_CLIENT_SECRET
    - secretKey: idp-issuer-url
      remoteRef:
        key: infra/headlamp
        property: idp-issuer-url
    - secretKey: oidc-callback-url
      remoteRef:
        key: infra/headlamp
        property: oidc-callback-url