apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultwarden-namespace.yaml
  - vaultwarden-netpol.yaml
  - vaultwarden-externalsecret.yaml
  - vaultwarden-pvc.yaml
  - vaultwarden-deployment.yaml
  - vaultwarden-service.yaml
  - vaultwarden-ingress.yaml
