apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatus-helmrepository.yaml
  - gatus-configmap-env.yaml
  - gatus-configmap-config.yaml
  - gatus-externalsecret.yaml
  - gatus-mikrotik-externalsecret.yaml
  - gatus-networkpolicy.yaml
  - gatus-helmrelease.yaml
