apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: termix-oidc
  namespace: termix
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: termix-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: apps/termix
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: apps/termix
        property: OAUTH_CLIENT_SECRET
