apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fm-secrets
  namespace: firewall-manager-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fm-secrets
    creationPolicy: Owner
  data:
  - secretKey: FLASK_SECRET_KEY
    remoteRef:
      key: firewall-manager/dev/app
      property: FLASK_SECRET_KEY
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: firewall-manager/dev/app
      property: ENCRYPTION_KEY
  - secretKey: DATABASE_URL
    remoteRef:
      key: firewall-manager/dev/app
      property: DATABASE_URL
  - secretKey: DB_PASSWORD
    remoteRef:
      key: firewall-manager/dev/postgres
      property: password
  - secretKey: POSTGRES_DB
    remoteRef:
      key: firewall-manager/dev/postgres
      property: database
  - secretKey: POSTGRES_USER
    remoteRef:
      key: firewall-manager/dev/postgres
      property: username
