apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daikin-prometheus-exporter-tokens
  namespace: home-exporters
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-worker
  resources:
    requests:
      storage: 100Mi