apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daikin-prometheus-exporter-secrets
  namespace: home-exporters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: daikin-prometheus-exporter-secrets
    creationPolicy: Owner
  data:
    - secretKey: DAIKIN_CLIENT_ID
      remoteRef:
        key: infra/home-exporters/daikin-prometheus-exporter
        property: DAIKIN_CLIENT_ID
    - secretKey: DAIKIN_CLIENT_SECRET
      remoteRef:
        key: infra/home-exporters/daikin-prometheus-exporter
        property: DAIKIN_CLIENT_SECRET
    - secretKey: DEVICE_NAMES
      remoteRef:
        key: infra/home-exporters/daikin-prometheus-exporter
        property: DEVICE_NAMES