apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: apps/vaultwarden
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: apps/vaultwarden
        property: OAUTH_CLIENT_SECRET
    - secretKey: admin-token
      remoteRef:
        key: apps/vaultwarden
        property: ADMIN_TOKEN
