apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-oidc
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/longhorn
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/longhorn
        property: OAUTH_CLIENT_SECRET
