apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: pihole-exporter
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - pihole
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
