{
 "title": "Kubernetes Time Sync",
 "tags": [
  "kubernetes",
  "timing",
  "ntp",
  "node-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Clock Offset by Node (absolute)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "abs(node_timex_offset_seconds{job=\"node-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NTP Sync Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_timex_sync_status{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node UTC Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Estimated Clock Error",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}