apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgres-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
