apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding-namespace.yaml
  - linkding-netpol.yaml
  - linkding-oidc-externalsecret.yaml
  - linkding-pvc.yaml
  - linkding-deployment.yaml
  - linkding-service.yaml