apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - unbound-namespace.yaml
  - dns-netpol.yaml
  - unbound-configmap.yaml
  - unbound-deployment.yaml
  - unbound-service.yaml
  - unbound-pdb.yaml
  - unbound-exporter-service.yaml
  - unbound-ghcr-externalsecret.yaml
