output "client_id" {
  description = "OAuth2 client ID generated by Authentik"
  value       = authentik_provider_oauth2.provider.client_id
  sensitive   = true
}

output "client_secret" {
  description = "OAuth2 client secret generated by Authentik"
  value       = authentik_provider_oauth2.provider.client_secret
  sensitive   = true
}

output "application_slug" {
  description = "Application slug (used in OIDC discovery URL path)"
  value       = authentik_application.app.slug
}

output "application_uuid" {
  description = "Application UUID"
  value       = authentik_application.app.uuid
}

output "provider_id" {
  description = "OAuth2 provider ID"
  value       = authentik_provider_oauth2.provider.id
}

output "group_ids" {
  description = "Map of group name to group ID"
  value       = { for k, v in authentik_group.groups : k => v.id }
}
