apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-namespace.yaml
  - cert-manager-helmrepository.yaml
  - cert-manager-helmrelease.yaml
  - cert-manager-cloudflare-api-token-externalsecret.yaml
  - cert-manager-clusterissuer-letsencrypt.yaml
