apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - semaphoreui-namespace.yaml
  - semaphoreui-netpol.yaml
  - semaphoreui-helmrepository.yaml
  - semaphoreui-externalsecret.yaml
  - semaphoreui-oidc-externalsecret.yaml
  - semaphoreui-postgres-externalsecret.yaml
  - semaphoreui-postgres-pvc.yaml
  - semaphoreui-postgres-deployment.yaml
  - semaphoreui-postgres-service.yaml
  - semaphoreui-helmrelease.yaml
