apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphoreui-oidc
  namespace: semaphoreui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: semaphoreui-oidc
    creationPolicy: Owner
    template:
      data:
        client-id: "{{ .OAUTH_CLIENT_ID }}"
        client-secret: "{{ .OAUTH_CLIENT_SECRET }}"
        values.yaml: |
          oidc:
            providers:
              authentik:
                client_id: "{{ .OAUTH_CLIENT_ID }}"
                client_secret: "{{ .OAUTH_CLIENT_SECRET }}"
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: infra/semaphoreui
        property: OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: infra/semaphoreui
        property: OAUTH_CLIENT_SECRET