apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphoreui-postgres-pvc
  namespace: semaphoreui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
