apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphoreui-oidc
  namespace: semaphoreui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: semaphoreui-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/semaphoreui
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/semaphoreui
        property: OAUTH_CLIENT_SECRET
