apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphoreui-secrets
  namespace: semaphoreui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: semaphoreui-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_ADMIN_PASSWORD
    - secretKey: email
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_ADMIN_EMAIL
    - secretKey: fullname
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_ADMIN_FULLNAME
    - secretKey: cookieHash
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_COOKIE_HASH
    - secretKey: cookieEncryption
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_COOKIE_ENCRYPTION
    - secretKey: accesskeyEncryption
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_ACCESS_KEY_ENCRYPTION
    - secretKey: token
      remoteRef:
        key: infra/semaphoreui
        property: SEMAPHORE_RUNNER_TOKEN
