apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphoreui-postgres-secrets
  namespace: semaphoreui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: semaphoreui-postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: infra/semaphoreui
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: infra/semaphoreui
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: infra/semaphoreui
        property: POSTGRES_DB
