services:
  # --- Redis ---
  redis:
    image: redis:alpine
    networks:
      - auth-net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s

  # --- Database ---
  postgresql:
    image: postgres:16-alpine
    networks:
      - auth-net
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql/data

  # --- Authentik ---
  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    command: server
    networks:
      - auth-net
      - vlan200
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_HOST_BROWSER: https://authentik.${CLOUDFLARE_DOMAIN}
    volumes:
      - authentik:/media
      - authentik:/templates

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    command: worker
    networks:
      - auth-net
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_HOST_BROWSER: https://authentik.${CLOUDFLARE_DOMAIN}
  # --- Gateway ---
  kong:
    image: kong:latest
    networks:
      auth-net:
      docker-bridge:
        ipv4_address: 172.25.0.3
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/etc/kong/kong.yml
      # Kong OIDC variables can be injected here if not using kong.yml for secrets
      KONG_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      KONG_OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    volumes:
        - /volume1/containers/kong/:/usr/local/etc/kong

networks:
  auth-net:
    driver: bridge
  docker-bridge:
    external: true
  vlan200:
    external: true

volumes:
  database:
  authentik:
  
