apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/read-timeout: "3600000"
spec:
  ingressClassName: kong
  rules:
    - host: "storage.${DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
