apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-prometheus-token
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-prometheus-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: infra/vault
        property: prometheus-metrics-token
