apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/part-of: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/grafana
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/grafana
        property: OAUTH_CLIENT_SECRET
