apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mcp-rbac.yaml
  - mcp-externalsecret.yaml
  - mcp-inject-api-key-config-externalsecret.yaml
  - mcp-deployment.yaml
  - mcp-service.yaml
  - kong-plugin-mcp-key-auth.yaml
  - kong-plugin-mcp-bearer-to-apikey.yaml
  - kong-plugin-mcp-oidc.yaml
  - mcp-ingress.yaml
