apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelly-prometheus-exporter-secrets
  namespace: home-exporters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: shelly-prometheus-exporter-secrets
    creationPolicy: Owner
  data:
    - secretKey: SHELLY_AUTH_KEY
      remoteRef:
        key: infra/home-exporters/iot-shelly-prometheus-exporter
        property: cloud-key
    - secretKey: SHELLY_SERVER_URI
      remoteRef:
        key: infra/home-exporters/iot-shelly-prometheus-exporter
        property: server
