apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-pvc
  namespace: termix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-worker
  volumeName: pvc-f22170b9-524a-420c-ba50-ff03d055120f
  resources:
    requests:
      storage: 100Mi