services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    hostname: termix
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /volume1/containers/termix/:/app/data
    networks:
      - vlan200
      - bridge
    environment:
      PORT: "3000"
      TZ: 'Europe/Amsterdam'
    # env_file:
    #   - .env
    
networks:
  vlan200:
    external: true
