services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    hostname: termix
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /volume1/containers/termix/:/app/data
    networks:
      - docker-bridge
    environment:
      PORT: "3000"
      TZ: 'Europe/Amsterdam'
    # env_file:
    #   - .env
    
networks:
  docker-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
