services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    hostname: termix
    restart: unless-stopped
    volumes:
      - /volume1/containers/termix/:/app/data
    networks:
      docker-bridge:
        	ipv4_address: 172.25.0.2
    environment:
      PORT: "3000"
      TZ: 'Europe/Amsterdam'
# Network bridge for inline-management
networks:
  docker-bridge:
    driver: bridge
    name: docker-bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
