apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-pvc
  namespace: termix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-worker
  resources:
    requests:
      storage: 100Mi