apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - local-path-namespace.yaml
  - local-path-netpol.yaml
  - local-path-rbac.yaml
  - local-path-configmap.yaml
  - local-path-deployment.yaml
  - local-path-storageclass.yaml
  # Manage the pre-existing local-path SC to enforce is-default-class: "false"
  # (longhorn-worker is the cluster default).
  - local-path-default-storageclass.yaml
