apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: PG_USER
      remoteRef:
        key: services/identity/authentik
        property: PG_USER
    - secretKey: PG_PASSWORD
      remoteRef:
        key: services/identity/authentik
        property: PG_PASSWORD
    - secretKey: PG_DB
      remoteRef:
        key: services/identity/authentik
        property: PG_DB
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: services/identity/authentik
        property: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_HOST_BROWSER
      remoteRef:
        key: services/identity/authentik
        property: AUTHENTIK_HOST_BROWSER
