apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16.14-alpine3.23
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: PG_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: PG_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: authentik-db-pvc
