apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - authentik-namespace.yaml
  - authentik-pvc.yaml
  - authentik-externalsecret.yaml
  - authentik-configmap.yaml
  - authentik-redis-deployment.yaml
  - authentik-redis-service.yaml
  - authentik-postgres-deployment.yaml
  - authentik-postgres-service.yaml
  - authentik-deployment.yaml
  - authentik-service.yaml
