apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openwebui-externalsecret.yaml
  - openwebui-oidc-externalsecret.yaml
  - openwebui-kongkey-externalsecret.yaml
  - openwebui-pvc.yaml
  - openwebui-deployment.yaml
  - openwebui-service.yaml
  - openwebui-ingress.yaml
