apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: ai
spec:
  template:
    spec:
      containers:
        - name: openwebui
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openwebui-llm-gateway-key
                  key: OPENAI_API_KEY
