apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vendor/split/calico-crds.yaml
  - vendor/split/tigera-operator-crds.yaml
  - vendor/split/operator-runtime.yaml
  - installation.yaml
