apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kong-plugin-ai-proxy.yaml
  - kong-plugin-ai-proxy-anthropic.yaml
  - kong-ai-gateway-client-auth.yaml
  - kong-plugin-ai-prompt-guard.yaml
  - kong-plugin-normalize-model-name.yaml
  - kong-plugin-normalize-model-claude.yaml
  - kong-service-ai-gateway.yaml
  - kong-ai-gateway-models-ingress.yaml
  - kong-plugin-anthropic-openai-auth.yaml
  - kong-service-anthropic-openai-compat.yaml
  - kong-anthropic-openai-models-ingress.yaml
