---
all:
  children:
    control_plane:
      hosts:
        k8s-master01:
          ansible_host: 172.16.20.200
    workers:
      hosts:
        k8s-worker01:
          ansible_host: 172.16.20.201
        k8s-worker02:
          ansible_host: 172.16.20.202
        k8s-worker03:
          ansible_host: 172.16.20.203
    k8s_homelab:
      children:
        control_plane:
        workers:
