apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dsmr-p1-prometheus-exporter-configmap.yaml
  - dsmr-p1-prometheus-exporter-deployment.yaml
  - dsmr-p1-prometheus-exporter-service.yaml
  - dsmr-p1-prometheus-exporter-networkpolicy.yaml
