apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-admin
  namespace: ai
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-admin
  data:
    - secretKey: admin-email
      remoteRef:
        key: infra/openwebui
        property: admin-email
    - secretKey: admin-password
      remoteRef:
        key: infra/openwebui
        property: admin-password
