apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fm-secrets
  namespace: firewall-manager-staging
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fm-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: firewall-manager/staging/postgres
      property: password
  - secretKey: FLASK_SECRET_KEY
    remoteRef:
      key: firewall-manager/staging/app
      property: FLASK_SECRET_KEY
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: firewall-manager/staging/app
      property: ENCRYPTION_KEY
  - secretKey: POSTGRES_DB
    remoteRef:
      key: firewall-manager/staging/postgres
      property: database
  - secretKey: POSTGRES_USER
    remoteRef:
      key: firewall-manager/staging/postgres
      property: username
  - secretKey: DATABASE_URL
    remoteRef:
      key: firewall-manager/staging/app
      property: DATABASE_URL
