apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: goodwe-prometheus-exporter-secrets
  namespace: home-exporters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: goodwe-prometheus-exporter-secrets
    creationPolicy: Owner
  data:
    - secretKey: GOODWE_IP
      remoteRef:
        key: infra/home-exporters/goodwe-prometheus-exporter
        property: GOODWE_IP
