apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - goodwe-prometheus-exporter-configmap.yaml
  - goodwe-prometheus-exporter-externalsecret.yaml
  - goodwe-prometheus-exporter-deployment.yaml
  - goodwe-prometheus-exporter-service.yaml
  - goodwe-prometheus-exporter-networkpolicy.yaml
