apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daikin-prometheus-exporter-token-bootstrap
  namespace: home-exporters
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: daikin-prometheus-exporter-token-bootstrap
    creationPolicy: Owner
  data:
    - secretKey: tokens.json
      remoteRef:
        key: infra/home-exporters/daikin-prometheus-exporter
        property: TOKENS_JSON