apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daikin-prometheus-exporter-namespace.yaml
  - daikin-prometheus-exporter-configmap.yaml
  - daikin-prometheus-exporter-config-file-configmap.yaml
  - daikin-prometheus-exporter-externalsecret.yaml
  - daikin-prometheus-exporter-token-externalsecret.yaml
  - daikin-prometheus-exporter-pvc.yaml
  - daikin-prometheus-exporter-deployment.yaml
  - daikin-prometheus-exporter-service.yaml
  - daikin-prometheus-exporter-networkpolicy.yaml
