services:
  portainer:
      image: portainer/portainer-ee:2.40.0-alpine
      container_name: portainer
      hostname: portainer
      restart: always
      volumes:
        - /volume1/containers/core-infra/portainer/run/:/var/run/
        - /volume1/containers/core-infra/portainer/data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        vlan402:
          ipv4_address: 172.16.19.2

#Use VLAN402 Macdriver
networks:
  vlan402:
    external: true