apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portainer-oidc
  namespace: portainer
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: portainer-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/portainer
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/portainer
        property: OAUTH_CLIENT_SECRET
