apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vms-namespace.yaml
  - vms-netpol.yaml
  - vms-externalsecret.yaml
  - debian-bookworm-vm.yaml
  - debian-bookworm-ssh-service.yaml
