apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gatus-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/gatus
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/gatus
        property: OAUTH_CLIENT_SECRET
    - secretKey: cookie-secret
      remoteRef:
        key: infra/gatus
        property: OAUTH2_PROXY_COOKIE_SECRET
