---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ui-allow-oauth2-proxy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gatus
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: oauth2-proxy
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oauth2-proxy-allow-kong
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kong
      ports:
        - protocol: TCP
          port: 4180
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oauth2-proxy-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kong
      ports:
        - protocol: TCP
          port: 8443
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gatus
      ports:
        - protocol: TCP
          port: 8080
