apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forgejo-namespace.yaml
  - forgejo-netpol.yaml
  - forgejo-configmap.yaml
  - forgejo-externalsecret.yaml
  - forgejo-oidc-externalsecret.yaml
  - forgejo-pvc.yaml
  - forgejo-deployment.yaml
  - forgejo-service.yaml
