apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forgejo-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: apps/forgejo
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: apps/forgejo
        property: OAUTH_CLIENT_SECRET
