apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forgejo-secrets
    creationPolicy: Owner
  data:
    - secretKey: FORGEJO__security__SECRET_KEY
      remoteRef:
        key: apps/forgejo
        property: FORGEJO__security__SECRET_KEY
    - secretKey: FORGEJO__security__INTERNAL_TOKEN
      remoteRef:
        key: apps/forgejo
        property: FORGEJO__security__INTERNAL_TOKEN
    - secretKey: FORGEJO__oauth2__JWT_SECRET
      remoteRef:
        key: apps/forgejo
        property: FORGEJO__oauth2__JWT_SECRET
