apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
data:
  USER_UID: "1000"
  USER_GID: "1000"
  FORGEJO__database__DB_TYPE: sqlite3
  FORGEJO__database__PATH: /data/forgejo.db
  FORGEJO__server__HTTP_PORT: "3000"
  FORGEJO__server__START_SSH_SERVER: "false"
