apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - openclaw-pvc.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - openclaw-externalsecret.yaml
  - openclaw-configmap.yaml
  - deployment.yaml
  - service.yaml
