apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: infra/cloudflare-tunnel
        property: tunnel-token
