apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-tunnel-namespace.yaml
  - cloudflared-netpol.yaml
  - cloudflare-tunnel-externalsecret.yaml
  - cloudflare-tunnel-deployment.yaml
patches:
  - path: cloudflare-tunnel-affinity-patch.yaml
