apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-pvc
  namespace: homebox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-worker
  resources:
    requests:
      storage: 1Gi
