apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homebox-namespace.yaml
  - homebox-netpol.yaml
  - homebox-externalsecret.yaml
  - homebox-pvc.yaml
  - homebox-deployment.yaml
  - homebox-service.yaml
  - homebox-ingress.yaml
