apiVersion: v1
kind: ConfigMap
metadata:
  name: fm-config
  labels:
    app: firewall-manager
data:
  FM_ENV: "staging"
  GIT_COMMIT_SHA: "7025afd9825a8c4a8d294e508a4c761d9982576f"
  GIT_REPO_URL: "https://github.com/ivanversluis/firewall-manager"