apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: dns
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/part-of: homelab-dns
stringData:
  FTLCONF_webserver_api_password: "change-me-now"
