apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/part-of: homelab-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: FTLCONF_webserver_api_password
      remoteRef:
        key: services/dns/pihole
        property: FTLCONF_webserver_api_password