apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/part-of: homelab-dns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-worker
  resources:
    requests:
      storage: 2Gi
