apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole-exporter
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app.kubernetes.io/name: pihole-exporter
  ports:
    - name: metrics
      port: 9617
      targetPort: metrics
      protocol: TCP
