apiVersion: v1
kind: Node
metadata:
  name: k8s-worker01
  labels:
    node.longhorn.io/create-default-disk: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: k8s-worker02
  labels:
    node.longhorn.io/create-default-disk: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: k8s-worker03
  labels:
    node.longhorn.io/create-default-disk: "true"