apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/headlamp
  - ../../../infra/external-secrets
  - ../../../infra/vault
  - ../../../infra/vault-config
  - ../../../infra/monitoring/kps
  - ../../../infra/monitoring/metrics-server
  - ../../../infra/nodes/labels 
  - ../../../platform/cloudflare-tunnel/k8s/cloudflare-tunnel-deployment.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cloudflare-tunnel
      namespace: cloudflared
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - k8s-master01
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
  target:
    kind: Deployment
    name: cloudflare-tunnel
    namespace: cloudflared