apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-oidc
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client-id
      remoteRef:
        key: infra/argocd
        property: OAUTH_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: infra/argocd
        property: OAUTH_CLIENT_SECRET
